name: umbrella
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  sqflite: 2.4.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env

  fonts:
    - family: Chakra Petch
      fonts:
        - asset: assets/fonts/chakra_petch/ChakraPetch-Regular.ttf
        - asset: assets/fonts/chakra_Petch/ChakraPetch-Light.ttf
          weight: 300
        - asset: assets/fonts/chakra_Petch/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/chakra_Petch/ChakraPetch-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/chakra_Petch/ChakraPetch-Bold.ttf
          weight: 700

    - family: Russo One
      fonts:
        - asset: assets/fonts/russo_one/RussoOne-Regular.ttf
